/**
 * Agent Identity Manager
 * 
 * 管理 Agent ID 的生成、持久化和加载
 * 确保 Agent ID 在重启后保持一致
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const os = require('os');

// 默认配置文件路径
const DEFAULT_CONFIG_DIR = path.join(os.homedir(), '.f2a');
const DEFAULT_CONFIG_FILE = path.join(DEFAULT_CONFIG_DIR, 'identity.json');

class IdentityManager {
  constructor(options = {}) {
    this.configDir = options.configDir || DEFAULT_CONFIG_DIR;
    this.configFile = options.configFile || DEFAULT_CONFIG_FILE;
    this._identity = null;
  }

  /**
   * 获取或创建 Agent ID
   * @param {string} preferredId - 用户指定的 Agent ID（可选）
   * @returns {Object} { agentId, isNew, isPersistent }
   */
  getOrCreateIdentity(preferredId = null) {
    // 1. 如果用户指定了 ID，使用用户指定的
    if (preferredId) {
      const identity = {
        agentId: preferredId,
        createdAt: new Date().toISOString(),
        // publicKey: 预留字段，用于未来支持将公钥与身份绑定
        // 目前未使用，始终为 null
        publicKey: null
      };
      this._saveIdentity(identity);
      return { agentId: preferredId, isNew: true, isPersistent: true };
    }

    // 2. 尝试从配置文件加载
    const savedIdentity = this._loadIdentity();
    if (savedIdentity && savedIdentity.agentId) {
      return { 
        agentId: savedIdentity.agentId, 
        isNew: false, 
        isPersistent: true,
        createdAt: savedIdentity.createdAt 
      };
    }

    // 3. 生成新的随机 ID
    const newAgentId = this._generateAgentId();
    const identity = {
      agentId: newAgentId,
      createdAt: new Date().toISOString(),
      // publicKey: 预留字段，用于未来支持将公钥与身份绑定
      // 目前未使用，始终为 null
      publicKey: null
    };
    this._saveIdentity(identity);

    return { 
      agentId: newAgentId, 
      isNew: true, 
      isPersistent: true,
      isAutoGenerated: true
    };
  }

  /**
   * 生成随机 Agent ID
   */
  _generateAgentId() {
    // 生成一个易读的随机 ID: f2a-xxxx-xxxx
    const randomPart = crypto.randomBytes(4).toString('hex').slice(0, 8);
    return `f2a-${randomPart.slice(0, 4)}-${randomPart.slice(4)}`;
  }

  /**
   * 从配置文件加载身份
   */
  _loadIdentity() {
    try {
      if (fs.existsSync(this.configFile)) {
        const data = fs.readFileSync(this.configFile, 'utf8');
        return JSON.parse(data);
      }
    } catch (err) {
      console.error('[IdentityManager] Failed to load identity:', err.message);
    }
    return null;
  }

  /**
   * 保存身份到配置文件
   */
  _saveIdentity(identity) {
    try {
      // 确保配置目录存在
      if (!fs.existsSync(this.configDir)) {
        fs.mkdirSync(this.configDir, { recursive: true });
      }
      
      // 保存文件并设置权限为 0o600（只有所有者读写）
      fs.writeFileSync(this.configFile, JSON.stringify(identity, null, 2), { mode: 0o600 });
      this._identity = identity;
      return true;
    } catch (err) {
      console.error('[IdentityManager] Failed to save identity:', err.message);
      return false;
    }
  }

  /**
   * 重置身份（删除配置文件）
   */
  resetIdentity() {
    try {
      if (fs.existsSync(this.configFile)) {
        fs.unlinkSync(this.configFile);
      }
      this._identity = null;
      return true;
    } catch (err) {
      console.error('[IdentityManager] Failed to reset identity:', err.message);
      return false;
    }
  }

  /**
   * 获取配置文件路径
   */
  getConfigPath() {
    return this.configFile;
  }

  /**
   * 检查是否已存在持久化身份
   */
  hasPersistentIdentity() {
    return fs.existsSync(this.configFile);
  }
}

module.exports = { IdentityManager, DEFAULT_CONFIG_DIR, DEFAULT_CONFIG_FILE };
